### ISSUE TITLE
Better description on Github and PyPi

### ISSUE THREAD

**Issue by andybak** [vintasoftware/tapioca-wrapper#120]
"Tapioca API wrapper" sounds like you're an API wrapper for a SaaS called Tapioca. Why not mention that you're a fast way to generate API wrappers? Or at least call yourself an "API wrapper generator" or something like that.

**Comment by filipeximenes** [comment]
Good point, thanks for bringing it up. 
Which do you think is better: "API wrapper generator" or "API client generator"?

**Comment by andybak** [comment]
Here's a cure for indecision - how about "API client wrapper generator"? ;-)

**Comment by filipeximenes** [comment]
That sounds like a lib that generates libs to wrap libs hahaha
I'll stick with "API client generator" for the description since the word "wrapper" is already in the name of the tool.

**Comment by filipeximenes** [comment]
Done, thanks @andybak!
