### ISSUE TITLE
Resouce aware get_api_root

### ISSUE THREAD

**Issue by humrochagf** [vintasoftware/tapioca-wrapper#156]
I am implementing a Tapioca Flavour and there are some cases where I need to use a different API root.

Then, checking the code I saw that it could be a solution for these cases to pass to the get_api_root function the resource name at this line:

https://github.com/vintasoftware/tapioca-wrapper/blob/master/tapioca/tapioca.py#L113

So it will help to mount the proper api root url on these cases

**Comment by filipeximenes** [comment]
Hmm, yes, that's probably a good idea!

**Comment by humrochagf** [comment]
I made a PR #157 with the change and a test to verify it.

I've added the parameter with a default to keep backwards compatibility with previous implementations

**Comment by filipeximenes** [comment]
Merged and published to PyPI

**Comment by epage** [comment]
Is Tapioca following semver?  I'm wanting to make sure we have our version constraints set up appropriately.

We have our own `Adapter` implementation with its own `get_api_root` and this change broke our implementation.  So either this was (1) unintended, (2) you aren't following semver, or (3) we aren't supposed to override this function.

**Comment by filipeximenes** [comment]
@epage yes we follow semver. That was my mistake, very sorry! I just pulled the version from PyPI. Will fix and make a new release.
