### ISSUE TITLE
[Questions] Any standard/pattern for default timeouts, retry and Exceptions? 

### ISSUE THREAD

**Issue by cacarrara** [vintasoftware/tapioca-wrapper#158]
Hello, guys.

1. I would like to know if there is any standard or pattern to set default timeouts
for Tapioca API calls. Since all the .get()/.post() parameters, for example, are passed
to requests proper method, I could set a default timeout on `get_request_kwargs`. But
do you know if this is the proper way to do it.

2. Besides that, is there any way to set retry policies to Tapioca calls? Or should the Tapioca
client (caller) do that?

3. The last question is about Exceptions. What is the proper way to catch/handle exception 
on a Tapioca client (consumer) without make it directly coupled with Tapioca? Anything like
`DjangoModel.DoesNotExist` for example?

Thanks a lot for your work and attention. Let me know if I couldn't be enough clear about
my doubts.

**Comment by cacarrara** [comment]
Quick update.

For the third question, I'm doing a kind of workaround:

On wrapper:
```python
from tapioca.exceptions import ClientError, ServerError

from .exceptions import MyCustomError

MyAPI = generate_wrapper_from_adapter(MyAPIClient)
MyAPI.ClientError = ClientError
MyAPI.ServerError = ServerError
MyAPI.MyCustomError = MyCustomError
```
So on consumer I do not need to import tapioca errors directly:
```python
from tapioca_myapi import MyAPI

api = MyAPI()

try:
    response = api.get_resource().get()
except MyAPI.ClientError as ex:
    handle_error()
```

**Comment by filipeximenes** [comment]
1. Yes `get_request_kwargs` is the best place to set this.
2. Yes, we don't want tapioca to set a default for this. I think this is more of an application level concern not something we can set in the lib
3. I really depends a lot on the context and how this is going to be used, your approach seems fine :)
