### ISSUE TITLE
Headers for method

### ISSUE THREAD

**Issue by arnaghosh** [vintasoftware/tapioca-wrapper#159]
Hello,
I saw that the Line 113 of adapters.py disregards the given value of headers/Content-Type and sets it to "application/json". Is there a specific reason for it? Wouldn't it be better to set the default value only if this argument is not passed? 
Specifically, replacing Line 113 with :-
```
    if 'Content-Type' not in arguments['headers']:
        arguments['headers']['Content-Type'] = 'application/json'
```
Also, is there a way to incorporate the method headers using the resource mapping dictionary itself? 
Thanks for the help in advance.

**Comment by filipeximenes** [comment]
Hi @arnaghosh, the code you are referring to is located in the `JSONAdapterMixin` class. This is a 'helper' mixin to simplify building wrappers that use JSON. If your client is not using JSON media types or has a non usual behavior regarding it I recommend either not using the `JSONAdapterMixin` or overriding `get_request_kwargs` to adapt it tou your use case.

Regarding the second question, unfortunately there's currently no way to do this via mapping dictionary.

**Comment by arnaghosh** [comment]
Great. Thanks for the clarification.
