### ISSUE TITLE
Help understanding resource mapping and the tapioca api

### ISSUE THREAD

**Issue by jkornblum** [vintasoftware/tapioca-wrapper#161]
This looks like a very helpful library.
I'm confused however on some basic usage.

Let's say I have a resource `projects`.
Typical RESTful API could have these endpoints / verbs
```
GET /projects
POST /projects
GET /projects/{id}
PUT /projects/{id}
DELETE /projects/{id}
```
If I set my resource mapping like

```
RESOURCE_MAPPING = {
    'project': {
        'resource': 'projects/{id}',
        'docs': 'http://www.documentation.com/link/to/resource/documentation'
    },
}
```

Then the two endpoints without parameter `{id}` do not work in tapioca.
Something like `client.project().post(data={ ... })` fails because `id` was not specified.

Do I need to have two resources one for with `{id}` and one without?
These represent the same resource (a project) so having two resource mappings to handle id/noid seems confusing.

Am I using this correctly?

**Comment by chocoelho** [comment]
@jkornblum Can you try passing `id` as an empty string, like `client.project(id='').post(data={ ... })`?

**Comment by jkornblum** [comment]
Haha yes that works -- I should have mentioned I can do that in my post.

Two notes
- that is harder to understand for end users, i.e. setting <int> id to an empty string. Its not a huge deal to document though.
- some web-servers do not treat `/projects` and `/projects/` as the same endpoint, passing empty string leaves the trailing `/`

**Comment by chocoelho** [comment]
> * that is harder to understand for end users, i.e. setting  id to an empty string. Its not a huge deal to document though.

@filipeximenes might be the proper person to answer here, but it's my understanding that this wouldn't be an usual path to take, that's maybe one of the reasons this is not documented

> * some web-servers do not treat `/projects` and `/projects/` as the same endpoint, passing empty string leaves the trailing `/`

Although may be a pain here to have two resources with just a difference of `{id}` parameter, this is one of the reasons on why having two resources would be best instead of using `id=''` approach. But again, @filipeximenes might be better to answer this than me.

**Comment by jkornblum** [comment]
Okay thank you.
I think for now if we use tapioca we'll pass id="" and if necessary use two resources.
