### ISSUE TITLE
get_api_root not working

### ISSUE THREAD

**Issue by lemesdaniel** [vintasoftware/tapioca-wrapper#164]
Hi, 

I try created get_api_root method, but not working 

```
def get_api_root(self, api_params):
        if api_params.get('sandbox'):
            return 'https://sandbox-app.vindi.com.br/api/v1/'
        return 'https://app.vindi.com.br/api/v1/'

```

api = Vindi(api_key='my_key', sandbox=True)

it returns me

TypeError: get_api_root() got an unexpected keyword argument 'resource_name'
Where am I going wrong?

**Comment by filipeximenes** [comment]
Hey, sorry, this was updated recently and we did not update docs. The correct signature for this method is: `def get_api_root(self, api_params, **kwargs):`

**Comment by filipeximenes** [comment]
I'll update the docs. I'll close this issue LMK in case this doesn't fixes your problem.
