### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/tapioca-wrapper#22]
There are two possible ways to deal with versioning:
1. Have different packages for different api version.
2. Allow wrappers to adapt to new versions.

I like option 1 because it keeps resource mapping simpler, but in other hand seems much more work having to create a new wrapper for minor changes. Eg.: facebook's API has 2.3 and 2.4 versions with very few changes.
We should look into how Raml and Swagger deal with it. If they natively support versioning, I'm in favor of also supporting it.

**Comment by phalt** [comment]
The simplest solution would be option one. It's very easy to roll out a new package for a new version. You are also keeping the versions separate, so there is no chance of using parts of an old version, and bits of the new one, which could cause issues.

Option two could be done by adapting the endpoint configuration to allow you to segment a set of URIs for different versions. This would support backwards compat for people who don't want to fully upgrade yet.

I'm erring on the side of option 1 here. We keep versions explicit between other python packages anyway, so this is in keeping with that convention :)

**Comment by filipeximenes** [comment]
For now versioning should be done by creating new wrappers. It anyone has a different idea, please comment here or open a new issue so we can discuss it.
