### ISSUE TITLE
Document on how to create flavours

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/tapioca-wrapper#23]
Documentation should have a section on how to create new flavours. This is specially important since the interface is changing quite a bit over versions.

This should explain what each Adapter method does and witch ones should be overwritten when creating a flavour.

**Comment by joncasdam** [comment]
I was just searching for this, as I thought about create a flavour to instagram

**Comment by filipeximenes** [comment]
@joncasdam yep, we are late on this ticket, this is priority.
But in short you should use the cookicutter to bootstrap the basics of the code:
https://github.com/vintasoftware/cookiecutter-tapioca

and maybe look into other wrappers (and the source of the adapter code https://github.com/vintasoftware/tapioca-wrapper/blob/master/tapioca/adapters.py) to get some clues about the methods available.

Otherwise if you have any questions send an email to contact@vinta.com.br and I can help you with specific issues you might have.

**Comment by joncasdam** [comment]
yes yes. I'm already looking into other flavours. Hope to add something soon.
