### ISSUE TITLE
tapioca-wrapper client template with cookiecutter

### ISSUE THREAD

**Issue by marctc** [vintasoftware/tapioca-wrapper#36]
I think that would be interesting that you provide a cookiecutter template for wrapping new API clients, even the files needed to create a new PyPI package.

**Comment by filipeximenes** [comment]
Yes, we definitely need a cookiecutter template!

**Comment by filipeximenes** [comment]
So I've created the basics of the package: https://github.com/vintasoftware/cookiecutter-tapioca
Still need:
- Test the cookiecutter with a real service
- Add a README to the cookiecutter with some explanation on how to use it
- Mention the cookiecutter in the documentation AND tapioca README

**Comment by marctc** [comment]
Thank you @filipeximenes . I'll try it with a tapioca that I'm currently developing :)
