### ISSUE TITLE
Document "max_pages" and "max_items" on "pages" method.

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/tapioca-wrapper#40]

**Comment by filipeximenes** [comment]
@era could you help with this?

**Comment by era** [comment]
Yes :), I should change the quickstart document ( https://github.com/vintasoftware/tapioca-wrapper/blob/master/docs/quickstart.md), right? Are there any other file?

**Comment by filipeximenes** [comment]
That's right, no other files.
