### ISSUE TITLE
Data deserialization

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/tapioca-wrapper#49]
It may be a good idea to have automatic data deserialization.
It should not rely on data models since it would make things very complicated, error prone and could break on simple API changes.

The only idea I have for now is regex based matching before doing deserializations. Although not 100% confident this will work properly... looks very error prone.

Any ideas on this?

**Comment by era** [comment]
Hello Filipe, 

What type of data do you think can be a problem? Things like pagination?  Because the other type of data (integers, date and etc) should follow the JSON spec, right?

Regards,

**Comment by filipeximenes** [comment]
This is the reverse process of issue #25 
Issue #25 works when data is leaving the tapioca client to be sent inside the request. It happens just before the ``dictionary`` data is passed to ``format_data_to_request`` method. This means that if there is a Python ``Date`` object, it should be converted to a text format: ``02-11-2015``.

This issue is about data coming back after the request, aka the response. I would be nice if when we accessed a date field in the tapioca response object it was Python ``Date`` object instead of a date formated string.

This is much harder to design than issue #25.

**Comment by era** [comment]
Do you think that supporting the ISO 8601 and rfc822 standards for date is enough? If so, we could do like: https://github.com/bear/python-twitter/blob/master/twitter/status.py#L192 (using also https://github.com/boxed/iso8601).

**Comment by filipeximenes** [comment]
Well, they both should be supported, pluss tons of other data formats, for example: Decimals. 
But the important here is not what formats will be supported. It's more about having a generic design that allows each client to freely define their own serializations. 
Also, we have to be careful to keep the wrappers API consitent (make sure developers always know what they are expecting from each call). 

I've been talking with @aericson and I think we have a design idea that might work. Will try to post some sketches of it here.

**Comment by filipeximenes** [comment]
So... this the first design that pops in my mind:

## Usage
Since is very hard to automatically predict what is the actual type of the data being deserialized (neither would this be good since wouldn't be explicit to the user), we can let the user decide how to deserialize it. eg.:
``` python
response.start_date().to_date()
response.total_cost().to_decimal()
response.other_data_type().to_other_data_type()
```
This also complies with the current design we have since we need to call 
``` python
response.start_data().data()
``` 
to access the raw data (in this case probably a date formatted string). So it feels natural for me to be able to retrieve this data in another format using the ``to_date()``.

The conversion 'trigger' would be "any method starting with 'to_' " (or we could use 'as_' . eg: ``response.start_data().as_date()``). This would make TapiocaExecutor to start look for a conversion in the TapiocaAdapter.

## Customizing conversions
We would need a new class called ``Serializer`` that handles data conversion. This should be fully customizable by developers creating wrappers. The basic implementation would look something like this:
``` python
class Serializer(object):

	def deserialize(self, method, value):
		if hasattr(self, method):
			return getattr(self, method)(value)
	
	def to_date(self, value):
		return Date(value)

	def to_decimal(self, value):
		return Decimal(value)
``` 
Note that developers are encouraged to create any `to_` methods they wish.
Serializers could then be attached to Adapters declaratively:
``` python 
class ExampleClientAdapter(...):
	serializer = Serializer()

	def get_serializer(self):
		return self.serializer
```

## Important notes
- There should be a way for the developer exploring the wrapper to discover what are the available `to_` methods. 


@aericson @era comments, feedbacks, suggestions?

**Comment by era** [comment]
Seems really good :). I think we could use strategy pattern here, don't we? Because that way we allow the final user to choose between the flavour implementation or even one of his own. Something like:
      
      class ExampleClientAdapter(...):
         def __init__(serializerStrategy,...)
            self.serializer = serializerStrategy

          def get_serializer(self):
              return self.serializer

Also, I was thinking last night, maybe we could allow some meta-programming here. We could use __getattr__ to delegate all calls to "to_" methods to the serializer (so, even to_my_own_object would work here). What you think?

**Comment by turicas** [comment]
I'm currently working on a library to convert tabular data between many formats: [rows](https://github.com/turicas/rows). You may get some ideas from [`rows.fields`](https://github.com/turicas/rows/blob/develop/rows/fields.py).

**Comment by filipeximenes** [comment]
@era 
The strategy pattern sure looks interesting! We should definitely have this!
Yes, that's exactly the idea, any 'to_' method can be used and each wrapper (or strategy :)) can define it's own conversion.

@turicas 
This "detect_types" pattern is very cool. We should have a serializer that uses it. eg.:
``` python
class AutomaticSerializer(Serializer):
    def to_native(self, value):
        detected_types = detect_types(...)
        return detected_types.deserialize(value)
```
Can we easily use this as and external lib or will we need to make modifications before it works with tapioca?

**Comment by filipeximenes** [comment]
This is what I have so far:
https://github.com/vintasoftware/tapioca-wrapper/blob/serializers/tests/test_serializers.py

Feedbacks would be great. Could you guys take a look and play around a little bit?

**Comment by turicas** [comment]
@filipeximenes, yes, you can! Example:

```python
>>> from rows.fields import detect_types
>>> field_names = ['name', 'birthdate']
>>> field_values = [[u'Álvaro', '1987-04-29'], ['Other', '1990-01-01']]
>>> detected_types = detect_types(field_names, field_values)
>>> print detected_types
OrderedDict([('name', <class 'rows.fields.TextField'>), ('birthdate', <class 'rows.fields.DateField'>)])
```

And you can pass your own field types if you want more types to be detectable rather than the ones from `rows`. We currently have:

- `BoolField`
- `IntegerField`
- `FloatField`
- `DatetimeField`
- `DateField`
- `DecimalField`
- `PercentField`
- `TextField`
- `BinaryField`

Note that the order of `field_types` represents the priorities.

**Comment by turicas** [comment]
[remap](http://sedimental.org/remap.html) may be useful also.

**Comment by era** [comment]
About the https://github.com/vintasoftware/tapioca-wrapper/blob/serializers/tests/test_serializers.py.
The implementation it's really clean. I liked it :). It's very easy to use and to extend :).

@turicas I didn't know that libs. "Row" itself seems to be a good fit to be used inside the Serializers. 
@filipeximenes Are you guys avoiding using libs? (I'm asking because I know some people like to avoid if there's a way to implement without it)

**Comment by turicas** [comment]
@era, note that `rows` is in a state of active development and API may change before version `1.0.0` -- but I'm not planning to remove any feature (the features will be added but the API to access them may change).

**Comment by filipeximenes** [comment]
@era yes, I'd like to **avoid** adding external libs, but this is not a **must**.

Right now I'm struggling to decide between those:
1 - ``AutomaticSerializer`` available as a built in mixin, and have **rows** as a tapioca dependency
2 - ``AutomaticSerializer`` available as a built in mixin, with instructions saying that it needs to be set as dependency in the flavour if used. 
3 - ``AutomaticSerializer`` built into some ``DefaultSerializer`` set as default in the ``TapiocaAdapter``. Good point is that this way ``to_native()`` will be available by default to all wrappers giving some consistecy.
4 - Example implementation of ``AutomaticSerializer`` in the documentation on how to write a wrapper
5 - ``AutomaticSerializer`` as an external plugin lib with a reference in the how to write a wrapper documentation.

**Comment by era** [comment]
@filipeximenes The third option seems simpler, if I was an user, I would love it. I think the 4 make things more difficult, because someone who will develop a flavour already have a lot of things to worry about. Just my two cents.

**Comment by filipeximenes** [comment]
I've talked to @turicas, he will be extracting the type detection engine from ``rows`` and creating a new project just for it. We will wait for it before supporting ``to_native`` on default serializers.

I'll work on serializers documentation so we can launch it.
