### ISSUE TITLE
"data", "response" and "status_code" executor methods as attributes

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/tapioca-wrapper#77]
This is a design decision. I propose changing ``data``, ``response`` and ``status_code`` executor methods to be accessed as attributes instead of methods.

Current behaviour:
``` python
>>> response.some_data().data()
"this is a raw data"
```

Proposed behaviour:
``` python
>>> response.some_data().data
"this is a raw data"
````

**Comment by filipeximenes** [comment]
@era @turicas @aericson @vu3jej 
what do you think?

**Comment by era** [comment]
In my opinion the proposed behavior is easier to understand. When I started to use tapioca I always had some doubts about the .data() behaviour, transforming it in a attribute would solve my initial doubts.

Also we have: https://github.com/vintasoftware/tapioca-wrapper/issues/49

And in my opinion it's more elegant this:
```
>>> response.some_data().data
>>> response.some_data().to_decimal()
```
than:
```
>>> response.some_data().data()
>>> response.some_data().to_decimal()
```

At least in the first case we let it clear that `.data` is not changing anything, while `to_` does some type of cast.

**Comment by aericson** [comment]
looks good :+1:

**Comment by filipeximenes** [comment]
Cool!
