### ISSUE TITLE
Token requesting methods 

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/tapioca-wrapper#86]
```
Facebook.request_token()
Facebook.prompt_request_token()
```

**Comment by filipeximenes** [comment]
One note here: ``Facebook`` is a ``TapiocaInstantiator`` while it is not instantiated ``Facebook()``. So the two mentioned methods must be implemented in the ``TapiocaInstantiator`` and called by it as ``classmethods`` in the ``TapiocaAdapter``

**Comment by chocoelho** [comment]
Seeing https://github.com/vintasoftware/tapioca-wrapper/pull/89#issuecomment-303848998, should this issue be closed @filipeximenes ?
